spring.application.name=sbb
spring.devtools.livereload.enabled=true

# H2 데이터베이스 설정
# 인메모리 모드 (애플리케이션 실행 시에만 데이터 유지)
# spring.datasource.url=jdbc:h2:mem:testdb

# 파일 기반 임베디드 모드 (지정된 경로에 데이터 저장)
# 사전에 수동으로 생성 'test.mv.db' , 추후 자동 생성이 됩니다
#spring.datasource.url=jdbc:h2:~/test
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=

# MySQL 데이터베이스
spring.datasource.url=jdbc:mysql://localhost:3306/sbb
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# H2 콘솔 설정 (선택 사항)
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# ddl-auto 옵션 --> question / answer table 생성
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update